Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "postfix"
  config.vm.network :public_network, ip:"10.0.0.61"
  config.vm.network "forwarded_port", guest:587, host:587	
end
