---
hosts: testing# tasks file for git
vars:
tasks:
  - name: apt update
    apt: update_cache=yes

  - name: Install git package
    become: yes
    apt:
      name: "{{ item }}"
      state: present
      update_cache: no
    with_items:
        - git

- name: Clone into ~/Git
  git:
      repo: git://github.com/nonstopflights/Personal.git
      dest: "/home/aelchert/Git"
      clone: yes
      update: no
      accept_hostkey: yes
