---
- hosts: server

  vars:
    user: root
    password: CuIeyy7j!!

  handlers:
    - name: restart mysql
      service: name={{ mysql_service }} state=restarted

  tasks:
    - name: Install MySQL packages
      apt: pkg={{item}} state=installed
      with_items:
        - bundler
        - mysql-server-core-5.5
        - mysql-client-core-5.5
        - libmysqlclient-dev
        - python-mysqldb
        - mysql-server
        - mysql-client
        - build-essential

    - name: Remove the MySQL test database
      action: mysql_db db=test state=absent

    - name: Create databases
      mysql_db: name={{item}} state=present collation=utf8_general_ci encoding=utf8
      with_items:
          - booksread
          - lychee

    - name: Add deploy DB user and allow access to news_* databases
      mysql_user: name={{user}} password={{password}} host="%" priv=db1.*:ALL/db2.*:ALL,GRANT state=present


    - name: Set root password
      mysql_user: name=root password={{password}} host="{{item}}" priv=*.*:ALL,GRANT state=present
      with_items:
        - "{{ansible_hostname}}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: copy my.cnf file
      template: src=templates/my.cnf.j2 dest=/etc/mysql/my.cnf

    - name: Copy database dump file
      copy:
          src: templates/booksread_12-28-2016.sql
          dest: /tmp
      notify:
          - restart mysql

    - name: Restore database
      mysql_db:
        name: booksread
        state: import
        target: /tmp/booksread_12-28-2016.sql
      notify:
          - restart mysql
