---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  changed_when: false

- name: add nginx
  user:
    name: nginx
    comment: nginx
    groups: admin
    state: present

- name: Ensure nginx is installed
  apt: pkg={{ item }} state=present
  with_items:
    - nginx
    - python-passlib
    - htop
    - git

# Configure
- name: Configure nginx.config
  template:
    src: /home/aelchert/Git/Backups/Nginx/nginx.conf
    dest: /etc/nginx/nginx.conf owner=aelchert group=root mode=0644
  notify:
    - restart nginx
