Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "borgGUI"
  config.vm.network "public_network"
  config.vm.synced_folder "/mnt/Backups/", "/opt/Backups/", create: true
end
