---

- hosts: nginx
  tasks:
    - name: Install snmp and snmpd package
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - snmp
        - snmpd
        - snmp-mibs-downloader
    - name: Copy snmp file
      copy:
        src: files/snmpd.conf
        dest: /etc/snmp/snmpd.conf
        owner: aelchert
        group: root
        mode: 0644
    - name: restart snmp
      service:
        name: snmpd
        state: restarted
