Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "borgbackuptest"
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "public_network"
  config.vm.synced_folder "/Users/adamschoonover/Git/Dev_Projects/wedding_website", "/concrete", create: true
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
SHELL
end
