---
- name: Install required packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - php5
    - php5-cli
    - php5-common
    - php5-imagick
    - php5-gd
    - php5-json
    - libphp-pclzip

- name: Git Clone Lychee
  git:
    repo: https://github.com/electerious/Lychee.git
    dest: "{{ app_location }}"
    clone: yes
  become: sudo
  notify:
    - Modify permissions on uploads

- name: Generate the database config
  template:
    src: data-config.php.j2
    dest: "{{ app_location }}/data/config.php"
    mode: 755

# - lineinfile:
#     dest: /etc/selinux/config
#     regexp: '^SELINUX='
#     line: 'SELINUX=enforcing'
