Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "observium"
  config.vm.network "forwarded_port", guest: 80, host: 81009
  config.vm.network "forwarded_port", guest: 161, host: 161  
  config.vm.network "forwarded_port", guest: 6556, host: 6556
  config.vm.network "forwarded_port", guest: 15672, host: 15672
  config.vm.network "forwarded_port", guest: 36602, host: 36602
	
  config.vm.network "public_network", bridge: "eth0"
  config.vm.synced_folder "/mnt/NAS/", "/opt/mnt/NAS/", create: true
  config.vm.provision "shell", inline:
    "sudo apt-get update && \ 
     sudo apt-get install -y git libapache2-mod-php5 php5-cli php5-mysql php5-gd php5-mcrypt php5-json php-pear snmp fping mysql-server mysql-client python-mysqldb rrdtool subversion whois mtr-tiny ipmitool graphviz imagemagick"


end
