Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "usenet"
  config.vm.network "forwarded_port", guest: 8085, host: 8085
  config.vm.network "forwarded_port", guest: 5050, host: 5050
  config.vm.network "forwarded_port", guest: 8090, host: 8090
  config.vm.network "public_network", ip: "10.0.0.56", bridge: "eth0"

  config.vm.synced_folder "/mnt/NAS/Downloads/", "/opt/Downloads/", create: true, 
	owner: "vagrant", group: "root"
  config.vm.synced_folder "/mnt/NAS/", "/opt/NAS/", create: true, 
	owner: "vagrant",
	group: "vagrant"
end
