Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "pi-hole"
  config.vm.network "forwarded_port", guest: 53, host: 53
  config.vm.network "forwarded_port", guest: 80, host: 80
  config.vm.network "public_network", ip: "10.0.0.105", bridge: "eth0"
  config.vm.synced_folder "./", "/synced", create: true
  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
SHELL
end
