# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "testboxVM.box"
  config.vm.network "private_network", ip: "192.168.99.100"
  config.vm.network "forwarded_port", guest: 22, host: 22

  config.vm.provision :ansible do |ansible|
    ansible.playbook = "site.yml"
  end
end
