---
- name: Install Requirements
  apt: pkg={{ item }} state=installed update_cache=yes cache_valid_time=3600
  with_items:
    - python-cheetah
    - git
- name: Make sure Couchpotato directory has correct ownership
  file: path={{ couchpotato_path }} state=directory owner={{ user_username }} group={{ user_group }} recurse=yes

- name: Make sure Couchpotato directory has correct ownership
  file: path={{ couchpotato_path }} state=directory owner={{ user_username }} group={{ user_group }} recurse=yes

- name: Get Couchpotato Code from GitHub
  git: repo={{ couchpotato_repo }} dest={{ couchpotato_path }} version={{ couchpotato_version }} update=no
  become: yes
  become_user: "{{ user_name }}"

- name: Update Couchpotato init.d script
  template: src=init.{{ ansible_os_family }} dest=/etc/init.d/{{ couchpotato_init_script }} owner=root group=root mode=0755
