Vagrant.configure("2") do |config|
	config.vm.box = "ubuntu/xenial64"
	config.vm.hostname = "gymApp"
	config.vm.network "forwarded_port", guest: 5000, host:5000 
	config.vm.network "public_network", bridge: "en6"
	#config.vm.synced_folder "./", "/opt/", create: true
end
