---
- name: Install the mysql packages
  apt: name="{{ item }}" state=present update_cache=yes
  with_items:
    - mysql-server
    - python-mysqldb
    - mysql-client

- name: Copy the my.cnf file
  template: src=my.cnf.j2 dest=~/.my.cnf mode=0600
  notify:
   - restart mysql

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_pass }}"
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ mysql_root_pass }}"
  with_items:
    - "{{ ansible_hostname }}"
    - localhost
    - 127.0.0.1
    - ::1

- name: ensure anonymous users are not in the database
  mysql_user: name='' host="{{ item }}" state=absent
  with_items:
      - localhost
      - "{{ ansible_hostname }}"

- name: remove the test database
  mysql_db: name=test state=absent

- name: Create Database
  action: mysql_db login_user=root login_password={{ mysql_root_password }} name="{{ item.name }}"
  with_items:  mysql_users
  when:  mysql_users is defined

- name: Adds required MySQL users
  mysql_user: login_user=root login_password={{ mysql_root_password }} user="{{ item.name }}" password="{{ item.password }}" priv="{{ item.privs }}"
  with_items:  mysql_users
  when:  mysql_users is defined

- name: create lychee username and password
  mysql_user: name=lychee password=lychee priv="*.*:ALL" state=present

- name: Create Booksread databases
  mysql_db:
    db: "{{ item }}"
    state: present
  with_items:
    - booksread
    - lychee
