# manage docker containers
# assuming docker is already installed
---
- hosts: serverRemote
  tasks:
    - name: install docker-py, required for anisble and docker-py
      pip:
        name: docker-py

    - name: Sabnzbd image deployment
      docker_container:
        name: sabnzbd
        image: linuxserver/sabnzbd
        state: started
        network_mode: bridge
        restart_policy: always
        ports:
          - "8085:8080"
        env:
          PGID: "1000"
          PUID: "1000"
          TZ: "EST"
        volumes:
          - /opt/sabnzbd/:/config
          - /mnt/NAS/Downloads:/downloads
          - /mnt/NAS/Incomplete:/incomplete-downloads
      tags: sabnzbd

    - name: Unifi image deployment
      docker_container:
        name: unifi
        image: linuxserver/unifi
        state: started
        network_mode: bridge
        restart_policy: always
        ports:
          - "8080:8080"
          - "8081:8081"
          - "8443:8443"
          - "8843:8843"
          - "8880:8880"
        env:
          PGID: "1000"
          PUID: "1000"
          TZ: "EST"
        volumes:
          - /opt/unifi:/config
      tags: unifi

    - name: Sonarr image deployment
      docker_container:
        name: Sonarr
        image: linuxserver/sonarr
        state: started
        network_mode: bridge
        restart_policy: always
        ports:
          - "8989:8989"
        env:
          PGID: "1000"
          PUID: "1000"
          TZ: "EST"
        volumes:
          - /home/aelchert/Git/Personal/Backups/Usenet/NzbDrone/config:/config
          - /mnt/NAS/Downloads:/downloads
          - /mnt/NAS/TV\ Shows:/tv
      tags: sonarr

    - name: Radarr image deployment
      docker_container:
        name: Radarr
        image: linuxserver/radarr
        state: started
        network_mode: bridge
        restart_policy: always
        ports:
          - "7878:7878"
        env:
          PGID: "1000"
          PUID: "1000"
          TZ: "EST"
        volumes:
          - /home/aelchert/Git/Personal/Backups/Usenet/Radarr/config:/config
          - /mnt/NAS/Downloads:/downloads
          - /mnt/NAS/Movies:/movies
        tags: radarr

    - name: Confirm Lychee Folders
      file:
        path: '{{ item }}'
        state: directory
        mode: 0777
        owner: aelchert
        recurse: yes
      items:
        - /opt/Lychee
        - /opt/Lychee/uploads
        - /opt/Lychee/data
      tags: lychee

    - name: Pull lychee Image
      docker_image:
        name: neosar/lychee-docker
        state: present
      tags: lychee


    - name: Lychee image deployment
      docker_container:
        name: Lychee
        image: neosar/lychee-docker
        state: started
        network_mode: bridge
        restart_policy: always
        ports:
          - "9995:80"
          - "3306:3306"
        volumes:
          - /opt/lychee/uploads/:/uploads/:rw
          - /opt/lychee/data:/data/:rw
        tags: lychee
