---
- hosts: testing

  vars_files:
    - vars.yml

  tasks:
    - name: Add group
      group:
        name: admin
        state: present
        system: yes

    - name: Add user
      user:
        name: "{{ userName }}"
        group: admin
        state: present

    - name: Add admin group to Sudoers
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^admin'
        line: 'admin ALL=(ALL:ALL) ALL'

    - authorized_key:
        user: "{{ userName }}"
        key: "{{ lookup('file','/Users/aschoonover/.ssh/id_rsa.pub')}}"


    - user: name=aelchert generate_ssh_key=yes ssh_key_bits=2048 ssh_key_file=.ssh/id_rsa





  #roles:
    # - nginx
    # - sabnzbd
    # - couchpotato
    # - nzbdrone
    # - transmission
    # - plex
