---
- hosts: testing

  vars:
    userName: aElchert
    userGroup: admin
    server_name: server

  tasks:
    - name: Add group
      group:
        name: admin
        state: present
        system: yes

    - name: Add user
      user:
        name: "{{ userName }}"
        group: admin
        state: present

    - name: Add admin group to Sudoers
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^admin'
        line: 'admin ALL=(ALL:ALL) ALL'

    - name: copy pub key to remote machine
      authorized_key:
        user: "{{ userName }}"
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

  roles:
    - git





  #roles:
    # - nginx
    # - sabnzbd
    # - couchpotato
    # - nzbdrone
    # - transmission
    # - plex
