---
- hosts: remoteServer
  vars:
    http_port: 80
    max_clients: 200
  tasks:
  - name: Copy /templates/fstab to server
    file:
      src: ./templates/fstab
      dest: /etc/fstab
      owner: root
    become: true
