Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "subdownloader"
  config.vm.network "public_network"
  config.vm.synced_folder "/mnt/NAS", "/opt/NAS", create: true
end
